theme: "hugo-PaperMod"
baseURL: http://claudia-chu.netlify.app
languageCode: en-us
title: Home

params:
    homeInfoParams:
        Title: Claudia Pik-Ki Chu
        Content: I am a former psychology and education researcher who is making a transition from academia into data science. My expertise includes statistical analyses, data modelling and visualisation, as well as measurement and assessment.
        
                This website records the side projects that I have carried out to explore data analysis on different topics. 

    socialIcons: # optional
        - name: Github
          url: https://github.com/cpkchu
        - name: Twitter
          url: https://twitter.com/Claudia__Chu
        - name: LinkedIn
          url: https://www.linkedin.com/in/claudia--chu/
    
    defaultTheme: auto

